// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCCZK12Wd8Br_HMIwi13o4I5rHbJE0ApI',
    appId: '1:905371447196:web:780212b12586f119486259',
    messagingSenderId: '905371447196',
    projectId: 'otakuverse-afe63',
    authDomain: 'otakuverse-afe63.firebaseapp.com',
    storageBucket: 'otakuverse-afe63.appspot.com',
    measurementId: 'G-MP6BF1NMXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtExO2PUu9SPmujwjLj0qwroT6wkR5aKk',
    appId: '1:905371447196:android:28707b7703900f64486259',
    messagingSenderId: '905371447196',
    projectId: 'otakuverse-afe63',
    storageBucket: 'otakuverse-afe63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMXCQn242Z7blW0MoNaGcL5iOy38OyBP4',
    appId: '1:905371447196:ios:13777a2ad520df5c486259',
    messagingSenderId: '905371447196',
    projectId: 'otakuverse-afe63',
    storageBucket: 'otakuverse-afe63.appspot.com',
    iosClientId: '905371447196-0on9vqbf9h4haqu96pr9ql3jh5jhbfgi.apps.googleusercontent.com',
    iosBundleId: 'com.example.otakuverse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMXCQn242Z7blW0MoNaGcL5iOy38OyBP4',
    appId: '1:905371447196:ios:f50d5457f9904dd0486259',
    messagingSenderId: '905371447196',
    projectId: 'otakuverse-afe63',
    storageBucket: 'otakuverse-afe63.appspot.com',
    iosClientId: '905371447196-khhbm3ksjuccm0b355v39ptsfqu0jdim.apps.googleusercontent.com',
    iosBundleId: 'com.example.otakuverse.RunnerTests',
  );
}
